# Generated by Django 4.0.1 on 2022-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Model',
                'db_table': 'Home_model',
            },
        ),
    ]
