# Generated by Django 4.0.1 on 2022-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
